name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ./src/adt-auto-ingester.csproj
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: "./src/bin/Azure.*.ddl"
        # An explicit key for restoring and saving the cache
        key: adt-auto-ingestor-deps    
    - name: Build
      run: dotnet build ./src/adt-auto-ingester.csproj --no-restore   
    - name: Test
      run: dotnet test ./tests/adt-auto-ingester-tests.csproj --results-directory ./tests/test-results/
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: "./tests/test-results/**/*.xml"
    - name: InferSharp
      uses: microsoft/infersharpaction@v1.0
      with:
        # The path where the binaries (.dll and .pdb) are located.
        binary-path: "./src/bin"
    - name: Infer# analysis results
      run: echo "${{ steps.runinfersharp.outputs.results }}"
