name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Function App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ./src/adt-auto-ingester.csproj
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
        path: "./src/bin/Azure.*.ddl"
        key: adt-auto-ingestor-deps    
    - name: Build
      run: dotnet build ./src/adt-auto-ingester.csproj --no-restore   
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Unit Tests For Azure Digital Twin Auto Ingestor
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: tests/adt-auto-ingester-tests.csproj
          report_name: Azure Digital Twin Auto Ingester Test Results
          report_title: Azure Digital Twin Auto Ingestor Test Results
          gist_name: auto_ingester_tests.md
          gist_badge_label: 'Azure Digital Twin Auto Ingestor Tests: %Counters_passed%/%Counters_total%'     
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_token: ${{ secrets.GIST_TOKEN }}
          set_check_status_from_test_outcome: true
      
