name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: "bin/Azure.*.ddl"
        # An explicit key for restoring and saving the cache
        key: adt-auto-ingestor-deps
    - name: Build
      run: dotnet build --no-restore
    - name: Move Output for Analysis
      # You may pin to the exact commit or the version.
      # uses: canastro/copy-action@7ddff6fc153a2ea2cd0fb88ed9750544c051e399
      uses: canastro/copy-action@0.0.2
      with:
        # Source file
        source: "/home/runner/work/adt-auto-ingestor/adt-auto-ingestor/bin/Debug/netcoreapp3.1/adt-auto-injester.dll"
        # Target file
        target: "/home/runner/work/adt-auto-ingestor/adt-auto-ingestor/analysis/adt-auto-injester.dll"
    - name: InferSharp
      uses: microsoft/infersharpaction@v1.0
      with:
        # The path where the binaries (.dll and .pdb) are located.
        binary-path: "analysis"
    - name: Infer# analysis results
      run: echo "${{ steps.runinfersharp.outputs.results }}"
