name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ./src/adt-auto-ingester.csproj
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: "./src/bin/Azure.*.ddl"
        # An explicit key for restoring and saving the cache
        key: adt-auto-ingestor-deps    
    - name: Build
      run: dotnet build ./src/adt-auto-ingester.csproj --no-restore   
    - name: Test
      run: dotnet test ./tests/adt-auto-ingester-tests.csproj --results-directory ./tests/test-results/        
    - name: InferSharp
      uses: microsoft/infersharpaction@v1.0
      with:
        # The path where the binaries (.dll and .pdb) are located.
        binary-path: "./src/bin"
    - name: Infer# analysis results
      run: echo "${{ steps.runinfersharp.outputs.results }}"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Unit Tests For Azure Digital Twin Auto Ingestor
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: tests/adt-auto-ingester-tests.csproj
          report_name: auto_ingester_tests
          report_title: Azure Digital Twin Auto Ingestor Tests
          gist_name: auto_ingester_tests.md
          gist_badge_label: 'Azure Digital Twin Auto Ingestor Tests: %Counters_passed%/%Counters_total%'     
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_token: ${{ secrets.GIST_TOKEN }}
      
